src/objects/Position__c.object
<CustomObject>
    <description>Positions releted to the project</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>Information about SFDC projects</description>
    <label>Project</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectIDforPosition.cls
public with sharing class ProjectIDforPosition {
public ProjectIDforPosition(ApexPages.StandardController controller) {
        Position__c child = (Position__c)controller.getRecord();
        
        //if you always create the child object through relatedList
        //parent__c should not be null
        if (child.Project__c != null) {
            Project__c parent = [select name from Project__c where id =: child.Project__c limit 1];
            child.project__c = parent.name;
            system.debug('Hello This Jenkins 777');
        }
    }
}